### ISSUE TITLE
Does this work for more gene families?

### ISSUE THREAD

**Issue by XuewenWangUGA** [sablokgaurav/evolutionary_rate_analyer#1]
A Good R tool.

From the code, it seems this tool is suitable for one gene family, which may have many DNA sequences. Does this work for more gene families, which have many DNA sequences for each gene family ?

Could you please give example dataset and output?

Thanks.

Xuewen

**Comment by sablokgaurav** [comment]
@XuewenWangUGA thank you and you can use the sapply to map this function to any number of the sequences. If you have more than one fasta files, you can sapply or the lapply this function to all the individual fasta files. 

Alles super,
Gaurav
